### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by fr3fou** [streamich/ts-easing#4]
How would one use this library? Would they call that method inside a loop or what? Mind providing more examples?

**Comment by streamich** [comment]
let's say you want to move something from `10px` to `100px`, you normalize it to `[0, 1]`:

```
10px -> 0
100px -> 1
```

And let's say the animation should take 1 second, you call the easing functions every animation frame to compute the the position, let's say every 16ms:

```
easing.quadratic((0 * 16) / 1000) * ((100 - 10) + 10) + 'px'
// after 16 ms
easing.quadratic((1 * 16) / 1000) * ((100 - 10) + 10) + 'px'
// after 16 ms
easing.quadratic((2 * 16) / 1000) * ((100 - 10) + 10) + 'px'
// after 16 ms
easing.quadratic((3 * 16) / 1000) * ((100 - 10) + 10) + 'px'
// etc.
```

Hope it helps.

**Comment by fr3fou** [comment]
Would you do the `after 16ms` part with requestAnimationFrame()?

**Comment by streamich** [comment]
Usually, yes.

**Comment by fr3fou** [comment]
I see, thanks!
